import Head from "next/head";
import Script from "next/script";
import styles from "../styles/Home.module.css";
import Navigation from "@/components/Navigation";
import Carrousel from "@/components/Carrousel";
import Information from "@/components/Information";
import BlogComponent from "@/components/BlogComponent";
import Donation from "@/components/Donation";
import Subscription from "@/components/Subscriptions";
import Contact from "@/components/Contact";
import Footer from "@/components/Footer";
import theme from "@/styles/theme";
import NavItems from "@/components/NavItems";
import NavItemsMobile from "@/components/NavItemsMobile";

export default function Home() {
  const navItems = <NavItems />;
  const navItemsMobile = <NavItemsMobile />;

  return (
    <div className={styles.container}>
      <Head>
        <title>Fuhped</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main className={styles.main}>
        <Navigation
          backgroundColorOne={theme.palette.background.default}
          backgroundColorTwo={theme.palette.primary.third}
          textColorOne={theme.palette.text.main}
          textColorTwo={theme.palette.text.second}
          navItems={navItems}
          navItemsMobile={navItemsMobile}
        />
        <Carrousel />
        <Information />
        <BlogComponent />
        <Donation />
        <Subscription />
        <Contact />
        <Footer />
      </main>
    </div>
  );
}
