import Head from "next/head";
import styles from "../styles/Home.module.css";
import Carrousel from "@/components/Carrousel";
import Information from "@/components/Information";
import BlogComponent from "@/components/BlogComponent";
import Donation from "@/components/Donation";
import Subscription from "@/components/Subscriptions";
import Contact from "@/components/Contact";
import Footer from "@/components/Footer";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Fuhped</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Carrousel />
        <Information />
        <BlogComponent />
        <Donation />
        <Subscription />
        <Contact />
        <Footer />
      </main>
    </div>
  );
}
